main : GEMM_Simple.cpp GEMM_Blocking.cpp CSR_Implementation.cpp

simple : 
	g++ GEMM_Simple.cpp -o GEMM_Simple
	./GEMM_Simple

	rm -f GEMM_Simple

blocking :
	g++ GEMM_Blocking.cpp -o GEMM_Blocking
	./GEMM_Blocking

	rm -f GEMM_Blocking

CSR :
	g++ CSR_Implementation.cpp -o CSR_Implementation
	./CSR_Implementation

	rm -f CSR_Implementation